

services:
  postgres_db: 
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports: 
      - "5537:5432"
    
    environment:
      POSTGRES_USER: LOTTO_DB
      POSTGRES_PASSWORD: LOTTO_DB
      POSTGRES_DB: LOTTO_DB
    volumes:
     - pg_data:/var/lib/postgresql/pg_data

volumes:
  pg_data: